version: 2.1

jobs:
  do_begin:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            echo 'github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl' >> ~/.ssh/known_hosts
            echo 'github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=' >> ~/.ssh/known_hosts
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=' >> ~/.ssh/known_hosts
            cat ~/.ssh/known_hosts
            ssh git@github.com || echo

            ruby bin/deploy-context do_begin
  do_download:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            ruby bin/deploy-context do_download
  do_verify:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            ruby bin/deploy-context do_verify
  do_clean:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            ruby bin/deploy-context do_clean
  do_unpack:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            ruby bin/deploy-context do_unpack
  do_prepare:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            ruby bin/deploy-context do_prepare
  do_build:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            ruby bin/deploy-context do_build
  do_check:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            ruby bin/deploy-context do_check
  do_install:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu

            ruby bin/deploy-context do_install
  do_strip:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu

            ruby bin/deploy-context do_strip
  do_end:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            ruby bin/deploy-context do_end
  initialize:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            ruby bin/deploy-context do_end
  planning:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            ruby bin/deploy-context do_end
  execution:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            ruby bin/deploy-context do_end
  closure:
    docker:
      - image: cimg/ruby:3.1.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    environment: {}
    working_directory: /home/circleci/deploy-context
    steps:
      - checkout
      - run: |
            set -xu
            cucumber -t @closure
#...
workflows:
  version: 2
  build-deploy:
    jobs:
      - initialize:
          filters:
            branches:
              only: master
      - planning:
          filters:
            branches:
              only: master
      - execution:
          filters:
            branches:
              only: master
      - closure:
          filters:
            branches:
              only: master
