##YAML Template
<% default = "--no-snippets --no-source --no-duration --publish-quiet" %>
<% default = "--no-source --no-duration --publish-quiet" %>
<% default = "--no-source --publish-quiet" %>
<% common = "#{default} --exclude features_list/9.cucumber.feature" %>
preinit: <%= default %> --tags @preinit
initialize: <%= default %> --tags @initialize
planning: <%= default %> --tags @planning
execution: <%= default %> --tags @execution
closure: <%= default %> --tags @closure
post_mortem: <%= default %> --tags @post_mortem
wip: <%= default  %> --tags @wip --strict
knife: <%= default %> --tags @knife
kitchen: <%= default %> --tags @kitchen
rake: <%= default %> --tags @rake
git: <%= default %> --tags @git
habitat: <%= default %> --tags @habitat
cucumber: <%= default %> --tags @cucumber
install: <%= default %> --tags @install
inspec: <%= default %> --tags @inspec
supermarket: <%= default %> --tags @supermarket
cycle: <%= common %>
strict: <%= common %> --strict
html_report: <%= common %> --format html --out=features_report.html
