##YAML Template
<% default = "--no-snippets --no-source --no-duration --publish-quiet" %>
<% default = "--no-source --no-duration --publish-quiet" %>
<% common = "#{default} --tags @wip --strict" %>
preinit: <%= default %> --tags @preinit
initialize: <%= default %> --tags @initialize
planning: <%= default %> --tags @planning
execution: <%= default %> --tags @execution
closure: <%= default %> --tags @closure
post_mortem: <%= default %> --tags @post_mortem
strict: <%= common %>
html_report: <%= default %> --exclude features_list/6.cucumber.feature --format html --out=features_report.html
knife: <%= default %> --tags @knife
kitchen: <%= default %> --tags @kitchen
rake: <%= default %> --tags @rake
git: <%= default %> --tags @git
habitat: <%= default %> --tags @habitat
cucumber: <%= default %> --tags @cucumber
cycle: <%= default %> --exclude features_list/6.cucumber.feature
databags: <%= default %> --tags @databags
