##YAML Template
<% default = "--no-snippets --no-source --no-duration --publish-quiet" %>
<% default = "--no-source --no-duration --publish-quiet" %>
<% default = "--no-source --publish-quiet" %>
<% default = "--publish-quiet" %>
<% common = "#{default} --exclude features_list/9.cucumber.feature" %>
<% html_report = "#{common} --format html" %>
<% json_report = "#{common} --format json" %>
<%= %w(kitchen knife habitat git rake inspec install supermarket).map do |application|
  (
    [
      ["#{application}:", default, "--tags @#{application}"].join(' '),
      ["#{application}_html:", html_report, "--out=logs/html/#{application}_features_report.html", "--tags @#{application}"].join(' '),
      ["#{application}_json:", json_report, "--out=logs/json/#{application}_features_report.json", "--tags @#{application}"].join(' ')
    ] + %w(preinit initialize planning exsecution closure post_mortem).map do |step|
      [
        ["#{application}_#{step}:", default, "--tags @#{application}"].join(' '),
        ["#{application}_#{step}_html:", html_report, "--out=logs/html/#{application}_features_report.html", "--tags @#{application}", "--tags @#{step}"].join(' '),
        ["#{application}_#{step}_json:", json_report, "--out=logs/json/#{application}_features_report.json", "--tags @#{application}", "--tags @#{step}"].join(' ')
      ]
    end
  ).join("\n")
  end.join("\n")
%>

html_report: <%= html_report%> --out=logs/html/features_report.html